# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        reinforcement: 1
        reinforcement learning: 1
        imitation: 1
        imitation learning: 1
        represenattion: 1
        representation learning: 1

# 通知の閾値
score_threshold: 0
